# Site
title: Thinh Tran
author: Kei Nart

# Linked
freecodecamp: https://freecodecamp.org/thinhtranhnvn
codepen: https://codepen.io/thinhtranhnvn
github: https://github.com/thinhtranhnvn
youtube: https://www.youtube.com/channel/UC5j6yt-lodC3cTzQo1PaIAw
facebook: https://www.facebook.com/thinhtranhnvn

# Preference
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
